ST0 =  0  # Final Stage = Bloodlines
ARE =  1  # Colosseum
CAT =  2  # Catacombs
CEN =  3  # Center Cube
CHI =  4  # Abandoned Mine
DAI =  5  # Royal Chapel
DRE =  6  # Nightmare
LIB =  7  # Long Library
NO0 =  8  # Marble Gallery
NO1 =  9  # Outer Wall
NO2 =  10 # Olrox's Quarters
NO3 =  11 # Castle Entrance
NP3 =  12 # Castle Entrance (after visiting Alchemy Laboratory)
NO4 =  13 # Underground Caverns
NZ0 =  14 # Alchemy Laboratory
NZ1 =  15 # Clock Tower
TOP =  16 # Castle Keep
WRP =  17 # Warp rooms
RARE = 18 # Reverse Colosseum
RCAT = 19 # Floating Catacombs
RCEN = 20 # Reverse Center Cube
RCHI = 21 # Cave
RDAI = 22 # Anti-Chapel
RLIB = 23 # Forbidden Library
RNO0 = 24 # Black Marble Gallery
RNO1 = 25 # Reverse Outer Wall
RNO2 = 26 # Death Wing's Lair
RNO3 = 27 # Reverse Entrance
RNO4 = 28 # Reverse Caverns
RNZ0 = 29 # Necromancy Laboratory
RNZ1 = 30 # Reverse Clock Tower
RTOP = 31 # Reverse Castle Keep
RWRP = 32 # Reverse Warp rooms
BO0 =  33 # Olrox
BO1 =  34 # Legion
BO2 =  35 # Werewolf & Minotaur
BO3 =  36 # Scylla
BO4 =  37 # Doppleganger10
BO5 =  38 # Hippogryph
BO6 =  39 # Richter
BO7 =  40 # Cerberus
RBO0 = 41 # Trio
RBO1 = 42 # Beezlebub
RBO2 = 43 # Death
RBO3 = 44 # Medusa
RBO4 = 45 # Creature
RBO5 = 46 # Doppleganger40
RBO6 = 47 # Shaft/Dracula
RBO7 = 48 # Akmodan II
RBO8 = 49 # Galamoth